//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by W32Proto.rc
//
#define IDR_MENU1                       101
#define IDD_ABOUTBOX                    101
#define IDR_ACCELERATOR1                102
#define IDI_W32PROTO                    103
#define IDD_DIALOGBOX                   103
#define IDR_TOOLBAR                     108
#define IDXX_STATUSBAR                  109
#define IDXX_TIMER                      110
#define IDR_MEOW                        110
#define IDC_EDIT1                       1000
#define ID_FILE_SAVEAS                  40005
#define ID_FILE_EXIT                    40007
#define ID_OPTIONS_TITLE                40011
#define ID_HELP_CONTENT                 40012
#define ID_HELP_ABOUT                   40013
#define ID_BUTTON_NEW                   40023
#define ID_BUTTON_OPEN                  40024
#define ID_BUTTON_SAVE                  40025
#define ID_BUTTON_CUT                   40026
#define ID_BUTTON_COPY                  40027
#define ID_BUTTON_PASTE                 40028
#define ID_BUTTON_PRINT                 40029
#define ID_BUTTON_HELP                  40030

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        111
#define _APS_NEXT_COMMAND_VALUE         40031
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
